FROM node:21.1.0-alpine

RUN apk add --no-cache tzdata

WORKDIR /app

COPY package*.json ./

RUN npm install --no-audit --no-fund --prefer-offline

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
